FROM node:20-alpine
WORKDIR /app
COPY backend/package*.json ./
RUN npm install
COPY backend .
RUN npm run build && npm prune --production
ENV BACKEND_PORT=8080
EXPOSE 8080
CMD ["node","dist/index.js"]
