FROM node:20-alpine as build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
RUN npm install -g serve
ENV FRONTEND_PORT=5173
EXPOSE 5173
CMD ["serve", "-s", "dist", "-l", "5173"]
